language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis travis-sphinx
script:
- tox
after_success:
- travis-sphinx deploy
deploy:
  provider: pypi
  user: briggySmalls
  password:
    secure: Adhm5Sdk0t6qgqKWPeK6rUX9xix8MojpmPvr4hyqW7khIsW9Xgl0pCLn2ihzjm5WNE/zXRHIrNp/atj6eV+Huf7LylX4I74HJoMQ/BdnzJPwpY7XUC2aecP87PMi4rP9SZRpaOjEmCbOu5Br2CG7jy7UzpOV6uA2gYpVITkyA5R5TgbOPTYRhgkNRL29y3DanzhqOOruAm8g2fwg38RXHNpTNvqPlxCTAW82w+JE+RHuMzmAkx6CrP6ctoN0CZr/Gm9MR4ngbggieyLZF8/oe5lMfFq5UvuCEToIubyp4g4Fztd1B7X8a2k9VddnbP3PG/vfEbmQFuBCyVqxzEA0KfT/ojPOoUaAh4NtoBTF2gx9UDC8a4rntDAfP6UeATHckO2oIriXNN/OhLooiBmoF3E0jFhQl8Hf6/A/2XbhnKZyxVOgFkmYt8CO/zRVxChzGb/HJ+K9SJLxrNoUcW/2dLmiTPfuOVZ0mXp1ycNs/m9IZ4wpjEEoSHf7eq/nJUWaIxxqdxCUGfgW7SdyvFZ4C3CDvT9qtFfcWl1soF/hdSoRDsB/U7gUXmAIN36/fazJ0W4Q+pXUZSUZTI/TM48ZKC9y5SEM8bCybjYaDE2nFNMM73eh1HWDXCYga3MatbsZYcRnLA+XDnFUnU03OY2mxfRMeS4fzKGjL4orAl9eJWw=
  on:
    tags: true
